"""Creation des tables utilisateurs livres emprunts

Revision ID: 32b710edaa4d
Revises: 5ce72ec87388
Create Date: 2026-09-29 05:32:49.213387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b710edaa4d'
down_revision: Union[str, Sequence[str], None] = '5ce72ec87388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('telephone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'telephone')
    # ### end Alembic commands ###
