"""Creation des tables utilisateurs livres emprunts

Revision ID: 5ce72ec87388
Revises: 
Create Date: 2026-09-29 04:08:55.707428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce72ec87388'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emprunts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('date_emprunt', sa.Date(), nullable=False),
    sa.Column('date_retour', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprunts')
    op.drop_table('utilisateurs')
    op.drop_table('livres')
    # ### end Alembic commands ###
