"""Creation des tables utilisateurs livres emprunts

Revision ID: 7ae8694ade75
Revises: 85cc1d0fd550
Create Date: 2026-09-29 06:37:27.964477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae8694ade75'
down_revision: Union[str, Sequence[str], None] = '85cc1d0fd550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
