"""Creation des tables utilisateurs livres emprunts

Revision ID: 85cc1d0fd550
Revises: f7b5a59217e4
Create Date: 2026-09-29 06:28:04.115958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cc1d0fd550'
down_revision: Union[str, Sequence[str], None] = 'f7b5a59217e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
