"""Creation des tables utilisateurs livres emprunts

Revision ID: 89b71fe911f2
Revises: 32b710edaa4d
Create Date: 2026-09-29 05:38:22.231627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b71fe911f2'
down_revision: Union[str, Sequence[str], None] = '32b710edaa4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('motdepasse', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'motdepasse')
    # ### end Alembic commands ###
