"""Creation des tables utilisateurs livres emprunts

Revision ID: f7b5a59217e4
Revises: 89b71fe911f2
Create Date: 2026-09-29 06:18:20.830319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b5a59217e4'
down_revision: Union[str, Sequence[str], None] = '89b71fe911f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
